### ISSUE TITLE
Can't find/control device

### ISSUE THREAD

**Issue by foxriver76** [OpenXbox/xbox-smartglass-rest-python#13]
Everytime I try to find devices it responds with empty devices:
```json
{"devices":{},"success":true}
```
also when I try to control directly with the liveid it says console not available

```json
{"message":"Console info for FD003F65D1219026 is not available","success":false}
```

The Xbox is turned on and my Xbox App finds and can control the Xbox in a few seconds. It's an Xbox One X and installed versions on my laptop are: 
```json
"versions":{"xbox-smartglass-auxiliary":null,"xbox-smartglass-core":"1.0.10","xbox-smartglass-nano":null,"xbox-smartglass-rest":"0.9.5","xbox-smartglass-stump":"0.9.4","xbox-webapi":"1.1.3"}
```
Any suggestions from your side?

**Comment by tuxuser** [comment]
Can you please check if your firewall/user privileges block broadcast / multicast traffic over the local network?
Which operating system are you using?

**Comment by foxriver76** [comment]
I'm running Ubuntu 18.04 LTS. Disabling firewall via ufw disable changed nothing also I tried running the xbox-rest-server as root which also didn't change the behaviour.

**Comment by tuxuser** [comment]
Using the `ip` command one can check if an interface is multicast capable by:

```
ip link show eth0 | grep MULTICAST
```

To enable or disable multicast you can use:

```
sudo ip link set dev eth0 multicast [on|off]
```

Source: https://unix.stackexchange.com/a/407972

**Comment by foxriver76** [comment]
Multicast is enabled on my Interfaces. I'm not very familiar with network communication. 
```bash
sudo ifconfig
enp4s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether c8:5b:76:9f:fb:fc  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=4169<UP,LOOPBACK,RUNNING,MULTICAST>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Lokale Schleife)
        RX packets 195978  bytes 37464392 (37.4 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 195978  bytes 37464392 (37.4 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp5s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.178.37  netmask 255.255.255.0  broadcast 192.168.178.255
        inet6 2001:16b8:20f4:f00:80a6:b8fa:559c:ced5  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::ddfc:2af7:2f7f:bf20  prefixlen 64  scopeid 0x20<link>
        ether 90:cd:b6:3e:34:7f  txqueuelen 1000  (Ethernet)
        RX packets 1874543  bytes 1562937355 (1.5 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1392067  bytes 1216616048 (1.2 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

I also tried the xbox-smartglass-core lib a while ago. There I searched for devices in a loop until I found my Xbox. It sometimes took about 1-5 minutes.

**Comment by tuxuser** [comment]
Please see my updated response above ;)

**Comment by foxriver76** [comment]
First one unfortunately did not solve the problem. When trying to pass my ip interface to the variable, it seems to expect an integer there. 

```python
@classmethod
    def get_listener(cls, *args, **kwargs):
        sock = DatagramServer.get_listener(*args, **kwargs)
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        bind_addr = '192.168.178.1'
        mreq = struct.pack("4sl", socket.inet_aton(MULTICAST), bind_addr)
        sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)
```

```
ERROR in app: Exception on /device [GET]
Traceback (most recent call last):
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/xbox/rest/routes/device.py", line 11, in device_overview
    discovered = ConsoleWrap.discover().copy()
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/xbox/rest/consolewrap.py", line 21, in discover
    return Console.discover()
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/xbox/sg/console.py", line 214, in discover
    cls.__start_cls_protocol()
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/xbox/sg/console.py", line 133, in __start_cls_protocol
    cls.__protocol__.start()
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/gevent/baseserver.py", line 304, in start
    self.init_socket()
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/gevent/server.py", line 194, in init_socket
    self.socket = self.get_listener(self.address, self.family)
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/xbox/sg/protocol.py", line 83, in get_listener
    mreq = struct.pack("4sl", socket.inet_aton(MULTICAST), bind_addr)
struct.error: required argument is not an integer
127.0.0.1 - - [2018-08-31 14:36:55] "GET /device HTTP/1.1" 500 412 0.004617
```

**Comment by tuxuser** [comment]
Sorry, my fault
`socket.inet_aton('192.168.178.37')`

**Comment by foxriver76** [comment]
Still the same error:

```
[2018-08-31 14:56:00,118] ERROR in app: Exception on /device [GET]
Traceback (most recent call last):
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/xbox/rest/routes/device.py", line 11, in device_overview
    discovered = ConsoleWrap.discover().copy()
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/xbox/rest/consolewrap.py", line 21, in discover
    return Console.discover()
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/xbox/sg/console.py", line 214, in discover
    cls.__start_cls_protocol()
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/xbox/sg/console.py", line 133, in __start_cls_protocol
    cls.__protocol__.start()
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/gevent/baseserver.py", line 304, in start
    self.init_socket()
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/gevent/server.py", line 194, in init_socket
    self.socket = self.get_listener(self.address, self.family)
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/xbox/sg/protocol.py", line 83, in get_listener
    mreq = struct.pack("4sl", socket.inet_aton(MULTICAST), bind_addr)
struct.error: required argument is not an integer
127.0.0.1 - - [2018-08-31 14:56:00] "GET /device HTTP/1.1" 500 412 0.002395
```

**Comment by tuxuser** [comment]
I should have read the struct format string more precisely...

```py
bind_addr = '192.168.178.37'
mreq = socket.inet_aton(MULTICAST) + socket.inet_aton(bind_addr)
sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)
```

**Comment by foxriver76** [comment]
That syntax was correct, thanks. Unfortunately it still doesn't find my Xbox. Maybe I should try it from another device or in another network. 

Do you still have any ideas, where the problem could be?

**Comment by tuxuser** [comment]
Okay, glad the snippet works now. Is the bind addr still correct tho, it should be your wifi client address?!

There are 2 possible caveats left to check:
1. Is "IGMP" allowed in your Fritz!Box settings? You should find it in the filtering settings iirc.
2. Actually, the wifi card/driver could fuck up multicast communication. Try another wifi card / adapter and switch to wired connection, for testing.

**Comment by foxriver76** [comment]
IGMP is and was activated during testing. 
I will test it with a wired connection asap.

Thanks for the good support so far.

**Comment by foxriver76** [comment]
Tried with Ethernet cable on Xbox and Ethernet cable on laptop. Unfortunately also did not work. I will try it from an rock64 or an raspberry pi. If it works on my iPhone app then it is most likely a Problem with the laptop I think. Thanks for the support

**Comment by foxriver76** [comment]
setup the server on my Rock64 --> discovers the console with the first request.
