### ISSUE TITLE
Internal Server Error on log in

### ISSUE THREAD

**Issue by foxriver76** [OpenXbox/xbox-smartglass-rest-python#26]
Hi guys, 

I am receiving an internal server error whenever I try to log in and providing email and password. When a parameter is missing he responds with missing password or email, but when providing it, it produces an error 500.

Requesting via:
```
curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' -i 'http://192.168.178.65:5557/auth/login' --data 'email=test@gmail.com&password=test'
```

Response Body:
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

Versions:
```json
{"xbox-smartglass-auxiliary":null,"xbox-smartglass-core":"1.0.11","xbox-smartglass-nano":null,"xbox-smartglass-rest":"0.9.7","xbox-smartglass-stump":"0.9.4","xbox-webapi":"1.1.5"}
```

Tried it hosting the server on different devices and different networks.

**Comment by tuxuser** [comment]
Tried to replicate

```
$ curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' -i 'http://127.0.0.1:5557/auth/login' --data 'email=test@gmail.com&password=test'
HTTP/1.1 500 INTERNAL SERVER ERROR
Content-Type: application/json
Content-Length: 122
Date: Wed, 14 Nov 2018 13:15:48 GMT

{"message":"Login failed! Error: Could not log in with supplied credentials","success":false,"two_factor_required":false}
```
I agree, **HTTP Code 500** is a bad choice for this error.
Do you also got the userdata back tho? If not, please post the releveant part of the rest-server log.

**Comment by foxriver76** [comment]
```
[2018-11-14 16:42:59,872] WARNING in manager: Token Auth failed: No valid RefreshToken. Attempting auth via credentials
[2018-11-14 16:42:59,872] INFO in manager: Attempting user credentials auth
[2018-11-14 16:42:59,882] DEBUG in connectionpool: Starting new HTTPS connection (1): login.live.com
[2018-11-14 16:43:00,592] DEBUG in connectionpool: https://login.live.com:443 "GET /oauth20_authorize.srf?client_id=0000000048093EE3&redirect_uri=https%3A%2F%2Flogin.live.com%2Foauth20_desktop.srf&response_type=token&display=touch&scope=service%3A%3Auser.auth.xboxlive.com%3A%3AMBI_SSL&locale=en HTTP/1.1" 200 8193
[2018-11-14 16:43:00,610] ERROR in app: Exception on /auth/login [POST]
Traceback (most recent call last):
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/xbox/rest/routes/auth.py", line 53, in authentication_login_post
    app.authentication_mgr.authenticate()
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/xbox/webapi/authentication/manager.py", line 174, in authenticate
    self.access_token, self.refresh_token = self._windows_live_authenticate(self.email_address, self.password)
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/xbox/webapi/authentication/manager.py", line 228, in _windows_live_authenticate
    response = self.__window_live_authenticate_request(email_address, password)
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/xbox/webapi/authentication/manager.py", line 391, in __window_live_authenticate_request
    server_data = self.extract_js_object(resp.content, "ServerData")
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/xbox/webapi/authentication/manager.py", line 208, in extract_js_object
    return demjson.decode(matches[0])
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/demjson-2.2.4-py3.6.egg/demjson.py", line 5699, in decode
    return_stats=(return_stats or write_stats) )
  File "/home/moritz/anaconda3/lib/python3.6/site-packages/demjson-2.2.4-py3.6.egg/demjson.py", line 4915, in decode
    raise errors[0]
demjson.JSONDecodeError: Missing value for object property, expected ":"
127.0.0.1 - - [2018-11-14 16:43:00] "POST /auth/login HTTP/1.1" 500 412 0.753756

```

**Comment by tuxuser** [comment]
Thanks, makes sense now! Pushing an update soon

**Comment by foxriver76** [comment]
Thank you.

**Comment by tuxuser** [comment]
The problem was in the parsing section of webapi, fixed with following commit:
OpenXbox/xbox-webapi-python@09ea3831e0b3fdf40a1fbbc68c69146b7452b745

Dependency on xbox-webapi was explicitly set in rest server's setup.py now and a safeguard was added, it will catch those generic exceptions in the future.
Relevant commits:
4d42cd5d2a90bd113420ffb1c7ed514b05770a1f **Add xbox-webapi as dependency explicitly**
2e4270e40498662bfcd711d4f0431d7f6450e59c  **Catch generic exceptions in /auth/login aka AuthenticationManager.authenticate**

Version **0.9.8** of rest-server and built and pushed to PyPi as we speak.

**Comment by foxriver76** [comment]
Now the error seems more clear, but why I am receiving it?

```json
{"message":"Unhandled authentication error: 'DisplayClaims'","success":false,"two_factor_required":false}
```

Only happens when I am providing the correct login data.

**Comment by foxriver76** [comment]
Was like my fault, wasn't my main mail address of xbox live.
